# theme.toml
# Paleta de colores dinámica para Yazi
# Generado automáticamente por sys-theme — NO EDITAR

[manager]
cwd = { fg = "#e60026", bold = true }
hovered = { fg = "#0c0d12", bg = "#e60026", bold = true }
preview_hovered = { bg = "#16171f" }

find_keyword = { fg = "#ff3b5c", bold = true, italic = true }
find_position = { fg = "#ff3b5c", bg = "reset", italic = true }

marker_copied = { fg = "#00e676", bg = "#00e676" }
marker_cut = { fg = "#ff3b5c", bg = "#ff3b5c" }
marker_selected = { fg = "#ff3b5c", bg = "#ff3b5c" }

border_symbol = "│"
border_style = { fg = "#e60026" }

[status]
separator_open = ""
separator_close = ""

# Modo normal
mode_normal = { bg = "#e60026", fg = "#0c0d12", bold = true }
# Modo seleccion
mode_select = { bg = "#ff3b5c", fg = "#0c0d12", bold = true }
# Modo no establecido
mode_unset = { bg = "#ff3b5c", fg = "#0c0d12", bold = true }

progress_label = { fg = "#f8f9fa", bold = true }
progress_normal = { fg = "#e60026", bg = "#16171f" }
progress_error = { fg = "#ff3b5c", bg = "#16171f" }

[select]
border = { fg = "#e60026" }
active = { fg = "#0c0d12", bg = "#e60026", bold = true }
inactive = { fg = "#f8f9fa" }

[input]
border = { fg = "#e60026" }
title = { fg = "#e60026", bold = true }
value = { fg = "#f8f9fa" }
selected = { bg = "#e60026" }

[completion]
border = { fg = "#e60026" }
active = { bg = "#e60026", fg = "#0c0d12" }
inactive = { fg = "#f8f9fa" }

[help]
on = { fg = "#e60026", bold = true }
exec = { fg = "#ff3b5c" }
desc = { fg = "#f8f9fa" }
hovered = { bg = "#16171f", bold = true }
footer = { fg = "#474b5c" }

[filetype]
rules = [
    # Imágenes
    { mime = "image/*", fg = "#00e5ff" },
    # Videos
    { mime = "video/*", fg = "#ff3b5c" },
    # Audio
    { mime = "audio/*", fg = "#e60026" },
    # Archivos comprimidos
    { mime = "application/zip", fg = "#ffd600" },
    { mime = "application/gzip", fg = "#ffd600" },
    { mime = "application/x-tar", fg = "#ffd600" },
    { mime = "application/x-bzip*", fg = "#ffd600" },
    { mime = "application/x-7z-compressed", fg = "#ffd600" },
    { mime = "application/x-rar", fg = "#ffd600" },
    # Documentos
    { mime = "application/pdf", fg = "#ff3b5c" },
    # Scripts y código
    { url = "*.sh", fg = "#00e676", bold = true },
    { url = "*.py", fg = "#00e5ff", bold = true },
    { url = "*.rs", fg = "#ff3b5c", bold = true },
    { url = "*.c", fg = "#54a0ff", bold = true },
    { url = "*.cpp", fg = "#54a0ff", bold = true },
    # Por defecto
    { url = "*", fg = "#f8f9fa" }
]
