# miles_morales.conf - Hyprland Active Borders
$color_primary = rgba(ff1e43ff)
$color_primary_glow = rgba(ff5773ff)
$color_bg_dark = rgba(08080aff)
$color_bg_light = rgba(141419ff)
$color_inactive = rgba(202025ee)
