# config
# Configuración del demonio de notificaciones Mako - Symbiote Suit

font=Hack Nerd Font 10
background-color=#050505
text-color=#e8eaed
border-color=#ffffff
border-size=2
border-radius=8
padding=15
margin=10
default-timeout=5000

[urgency=low]
border-color=#3c4043

[urgency=high]
border-color=#ffffff
default-timeout=0
