# symbiote.conf - Hyprland Active Borders
$color_primary = rgba(ffffffff)
$color_primary_glow = rgba(888888ff)
$color_bg_dark = rgba(050505ff)
$color_bg_light = rgba(121212ff)
$color_inactive = rgba(222222ee)
