# autostart.conf
# Aplicaciones y demonios que inician junto con Hyprland

# Autenticación Polkit
exec-once = systemctl --user start hyprpolkitagent

# Utilidades de entorno
exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = mako

# OSD (Volume, Brightness)
exec-once = swayosd-server

# Portapapeles (wl-clipboard con clipse)
exec-once = clipse -listen

# Network Manager Applet (opcional si usas nmtui, pero buena como fallback visual)
# exec-once = nm-applet --indicator
