# input.conf
# Configuración de teclado, ratón y touchpad

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    # Velocidad del puntero (-1.0 a 1.0)
    sensitivity = 0

    # Comportamiento del foco
    follow_mouse = 1
    mouse_refocus = false

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        tap-to-click = true
        drag_lock = false
        scroll_factor = 0.8
    }
}

gestures {
    # Gestos de workspace con el touchpad (deslizar con 3 dedos)
    workspace_swipe = on
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 300
    workspace_swipe_invert = false
    workspace_swipe_min_speed_to_force = 20
    workspace_swipe_cancel_ratio = 0.5
}
