# monitors.conf
# Configuración de pantallas

# Sintaxis general:
# monitor=name,resolution,position,scale

# Configuración por defecto (auto-detectar monitor principal)
monitor = , preferred, auto, 1

# Ejemplo para monitor de alta frecuencia de refresco
# monitor = DP-1, 2560x1440@144, 0x0, 1

# Ejemplo de portatil
# monitor = eDP-1, 1920x1080@60, 0x0, 1
