# rules.conf
# Reglas de ventanas y espacios de trabajo

# -- Window Rules --

# Clipse (Portapapeles normal) debe flotar en el centro de la pantalla
windowrulev2 = float, class:(clipse)
windowrulev2 = size 622 652, class:(clipse)
windowrulev2 = center, class:(clipse)

# Scratchpad General (Terminal flotante on-demand)
windowrulev2 = float, class:^(scratchpad_term)$
windowrulev2 = size 85% 80%, class:^(scratchpad_term)$
windowrulev2 = center, class:^(scratchpad_term)$
windowrulev2 = dimaround, class:^(scratchpad_term)$
windowrulev2 = workspace special:scratchpad silent, class:^(scratchpad_term)$

# Clipse Scratchpad (Portapapeles flotante on-demand)
windowrulev2 = float, class:^(clipse_scratchpad)$
windowrulev2 = size 622 652, class:^(clipse_scratchpad)$
windowrulev2 = center, class:^(clipse_scratchpad)$
windowrulev2 = dimaround, class:^(clipse_scratchpad)$
windowrulev2 = workspace special:clipse_space silent, class:^(clipse_scratchpad)$

# Aplicaciones TUI Generales (btop, nmtui, pulsemixer, yazi, etc.)
windowrulev2 = float, class:^(floating_tui)$
windowrulev2 = center, class:^(floating_tui)$
windowrulev2 = size 70% 70%, class:^(floating_tui)$
windowrulev2 = dimaround, class:^(floating_tui)$

# Polkit y cuadros de diálogo
windowrulev2 = float, class:^(.*polkit.*)$
windowrulev2 = float, title:^(Open File|Save File|Abrir Archivo|Guardar Archivo)$

# Picture-in-Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$

# Evitar maximización forzada en ciertas apps
windowrulev2 = suppressevent maximize, class:.*
