# hyprpaper.conf
# Configuración simplificada y de alta compatibilidad para Omaspidy

# Cargar la imagen en memoria (Ruta absoluta obligatoria)
preload = /home/adri/.config/hypr/wallpaper.jpg

# Mapeo explícito para la pantalla de tu portátil eDP-1
wallpaper = eDP-1,/home/adri/.config/hypr/wallpaper.jpg

# Mantener IPC habilitado para depuración y control dinámico
ipc = on

# Ocultar el mensaje splash
splash = false
