general {
    lock_cmd = pidof hyprlock || hyprlock       # Ejecuta hyprlock si no esta activo
    before_sleep_cmd = loginctl lock-session    # Bloquea antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Enciende la pantalla al despertar
}

listener {
    timeout = 300                               # 5 minutos
    on-timeout = loginctl lock-session          # Acción al agotarse el tiempo (Bloquear)
}

listener {
    timeout = 600                               # 10 minutos
    on-timeout = hyprctl dispatch dpms off      # Apagar la pantalla (DPMS)
    on-resume = hyprctl dispatch dpms on        # Encender la pantalla al detectar actividad
}
