general {
    lock_cmd = pidof hyprlock || hyprlock       # Ejecuta hyprlock si no esta activo
    before_sleep_cmd = loginctl lock-session    # Bloquea antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Enciende la pantalla al despertar
}

listener {
    timeout = 300                               # 5 minutos
    on-timeout = loginctl lock-session          # Accion al agotarse el tiempo
}
