# hyprpaper.conf
# Optimizacion de eficiencia máxima

# Carga la imagen en la memoria
preload = ~/.config/hypr/wallpaper.jpg

# Aplica la imagen precargada a todos los monitores
wallpaper = ,~/.config/hypr/wallpaper.jpg

# Apagar completamente el Inter-Process Communication (IPC)
# Esto ahorra ciclos de CPU e hilos de bateria si no cambias
# el fondo de manera dinamica a traves de scripts o animaciones.
ipc = off

# Desactiva el mensaje inicial de hyprpaper para un arranque mas limpio
splash = false
